---
Formação Cientista de Dados - prof. Fernando Amaral
Gráficos Básicos
---
Histograma
```{r}
hist(trees$Height)
hist(trees$Height, main='Árvores', ylab='Frequência', xlab='Altura', col='blue')
hist(trees$Height, main='Árvores', ylab='Frequência', xlab='Altura', col='blue',
     density=20, breaks=20 )
```
Densidade
```{r}
densidade = density(trees$Height)
plot(densidade)
```
Densidade sobre o Histograma, parâmetro par
```{r}
# Executar com ctrl+shift+enter
hist(trees$Height, main=NULL, xlab=NULL, ylab=NULL)
par(new=TRUE)
plot(densidade)
```
Dispersão
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main='Árvores')
plot(trees$Girth, trees$Volume, ylab='Circunferência', xlab='Volume', col='green',
     main='Árvores')
# pch muda o elemento gráfico 
plot(trees$Girth, trees$Volume, ylab='Circunferência', xlab='Volume', col='green',
     main='Árvores', pch=20)

```
Muda tipo
```{r}
plot(trees$Girth, trees$Volume, ylab='Circunferência', xlab='Volume', col='blue',
     main='Árvores', pch=20, type='l')
```
Tremulação, diminui sobre posição
```{r}
plot(jitter(trees$Girth), trees$Volume, ylab='Circunferência', xlab='Volume',
     col='blue', main='Árvores')
```
Legenda com dimensão categórica 
```{r}
plot(CO2$conc, CO2$uptake, pch=20, col=CO2$Treatment)
legend('bottomright',legend=c('nonchilled','chilled'),cex=1,fill=c('black','red'))
```
Novos dados
```{r}
plot(trees)
```
Divisão da tela
```{r}
# Executar todo o bloco
split.screen(figs=c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```






